package co.edu.uniquindio.compiladores.proyecto.lexico

enum class Categoria {
ENTERO, DECIMAL, IDENTIFICADOR_CLASE, IDENTIFICADOR_VARIABLE,IDENTIFICADOR_METODO, PARENTESIS, CORCHETES, LLAVES,
    PALABRA_RESERVADA, SEPARADOR_COMA,SEPARADOR_PUNTO, FIN_SENTENCIA, OPERADOR_ARITMETICO,OPERADOR_LOGICO,
    OPERADOR_RELACIONAL, DESCONOCIDO, CADENA_CARACTERES, COMENTARIO_LINEA, COMENTARIO_BLOQUE, INCREMENTO, DECREMENTO
}