package co.edu.uniquindio.compiladores.proyecto.lexico

enum class Categoria {
ENTERO, DECIMAL, IDENTIFICADOR,PARENTESIS, CORCHETES_IZQ,CORCHETES_DER, LLAVES, PALABRA_RESERVADA, PUNTO, SEPARADOR_COMA,SEPARADOR_PUNTO, FIN_SENTENCIA,
OPERADOR_ARITMETICO,OPERADOR_LOGICO,PARENTESIS_IZQ, DESCONOCIDO, IDENTIFICADOR_VARIABLE
}