package co.edu.uniquindio.compiladores.proyecto.lexico

enum class Categoria {
    ENTERO, DECIMAL, IDENTIFICADOR, IDENTIFICADOR_CLASE, IDENTIFICADOR_VARIABLE,IDENTIFICADOR_METODO, PARENTESIS_IZQUIERDO,
    PARENTESIS_DERECHO, CORCHETE_IZQUIERDO,CORCHETE_DERECHO, LLAVE_IZQUIERDA, LLAVE_DERECHA, PALABRA_RESERVADA,
    SEPARADOR_COMA,SEPARADOR_PUNTO, FIN_SENTENCIA, OPERADOR_ARITMETICO,OPERADOR_LOGICO, OPERADOR_RELACIONAL,
    DESCONOCIDO, CADENA_CARACTERES, COMENTARIO_LINEA, COMENTARIO_BLOQUE, INCREMENTO, DECREMENTO,
}